server:
  port: 8083
  servlet:
    context-path: /goodbooks

spring:
  application:
    name: bookCatalogueService
  datasource:
    url: jdbc:h2:mem:cataloguedb
    driverClassName: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

bookinfo:
  url: "http://bookInformationService"
  basepath: goodbooks
  resource: books

bookrating:
  url: "http://bookRatingService"
  basepath: goodbooks
  resource: rating

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8700/eureka/