server:
  port: 8083
  servlet:
    context-path: /goodbooks

spring:
  datasource:
    url: jdbc:h2:mem:cataloguedb
    driverClassName: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

bookinfo:
  url: "http://localhost"
  port: 8081
  basepath: goodbooks
  resource: books

bookrating:
  url: "http://localhost"
  port: 8082
  basepath: goodbooks
  resource: rating